### ISSUE TITLE
The price type might be lossy for implementations

### ISSUE THREAD

**Issue by ford-prefect** [beckn/protocol-specifications#19]
The [Price](https://developers.beckn.org/Core/Schema/price) type uses JSON numbers. While the spec [does not mandate a representation](https://tools.ietf.org/html/rfc8259#section-6) in the implementation, it's reasonable to expect that most systems would use the [IEEE 754 floating point representation](https://en.wikipedia.org/wiki/IEEE_754).

The IEEE 754 representation is not suitable for representing money, as the fractional part is in base 2. For example, the decimal number `0.1` does not have a perfectly accurate representation in base 2.

Maybe it makes sense to introduce a money type with a higher-fidelity representation.

One simple representation might be to use two integers representing the whole number and fractional parts. These would still be JSON numbers (as the spec does not have the notion of integers), but we can require that implementors do not use fractional values.

**Comment by beckn-dev** [comment]
Thank you @ford-prefect for bringing this up. We shall definitely take it into consideration. We have been discussing about creating a core data type describing an exchange instrument containing integral and the fractional part with their respective (currency) units. For example, to describe **$10.25** we could use an integral value plus a [descriptor](https://github.com/beckn/protocol-specifications/blob/master/core/schema/0.8.0/descriptor.json) object to describe the currency as shown below. 
`
{
    "integral" : {
        "val" : 10,
        "currency" : {
            "id" : "840",
            "name" : "Dollar",
            "code" : "USD",
            "sym" : "$"
        }
    },
    "fractional" : {
        "val" : 25,
        "currency" : {
            "id" : "155",
            "name" : "Cent",
            "code" : "",
            "sym" : "¢"
        }
    }
}
`

**Comment by ford-prefect** [comment]
One thing -- I think it is better to keep the representational stuff outside of the transfer mechanism. So something like:

```json
{
  "currency": "USD"
  "integral": "10"
  "fractional": "25"
}
```

The currency can be specified as ISO 4217 with allowance for extension for non-specified currencies.

The rationale is that clients will likely want to choose their own method of rendering (possibly with localisation and accessibility considerations), so encoding that in the transport seems like it might be restrictive.

In case this all too much, a simple note in the type to signal that implementations should take care about precision might also be good enough.

**Comment by pkapustin** [comment]
We discussed this more with @ford-prefect and would like to propose using string-based `"integral.fractional"` format instead of `DecimalValue`.

For example, using `"10.5"` instead of `{"integral": "10", "fractional": "5"}`

Reasons:

- Currently, it is unclear how to correctly represent negative values and whether the minus sign is allowed in either of the strings representing integral and fractional parts.
- While `"integral.fractional"` is essentially equivalent to `DecimalValue`, it is a widely accepted format which is also simpler and easier to both encode and decode. Usage of `DecimalValue` requires development of custom encoders and decoders for all participating systems which is extra work and also is error-prone.
- We think that `"integral.fractional"` format is also more human-readable.

**Comment by beckn-dev** [comment]
This has been fixed using a type called DecimalValue
